package br.com.zup.cashmanagement.models;

import java.math.BigDecimal;
import java.time.LocalDate;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedEnum;

import br.com.zup.cashmanagement.converters.LocalDateConverter;
import br.com.zup.cashmanagement.enums.TipoConta;
import br.com.zup.cashmanagement.enums.TipoQrCode;
import lombok.Setter;

@DynamoDBTable(tableName = "QrCode")
@Setter
public class QrCode {

    private String id;
    private BigDecimal valor;
    private TipoQrCode tipo;

    //QrCode estatico
    private String alias;

    //QrCode dinamico
    private Long banco;
    private TipoConta tipoConta;
    private Long agencia;
    private Long conta;
    private String url;
    private String indentificador;
    private BigDecimal juros;
    private BigDecimal multa;
    private BigDecimal desconto;
    private BigDecimal abatimento;
    private LocalDate vencimento;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public BigDecimal getValor() {
        return valor;
    }

    @DynamoDBAttribute
    public String getAlias() {
        return alias;
    }
    
    @DynamoDBTypeConvertedEnum
    public TipoQrCode getTipo() {
        return tipo;
    }

    @DynamoDBAttribute
    public Long getBanco() {
        return banco;
    }

    @DynamoDBTypeConvertedEnum
    public TipoConta getTipoConta() {
        return tipoConta;
    }

    @DynamoDBAttribute
    public Long getAgencia() {
        return agencia;
    }

    @DynamoDBAttribute
    public Long getConta() {
        return conta;
    }

    @DynamoDBAttribute
    public String getUrl() {
        return url;
    }

    @DynamoDBAttribute
    public String getIdentificador() {
        return indentificador;
    }

    @DynamoDBAttribute
    public BigDecimal getJuros() {
        return juros;
    }

    @DynamoDBAttribute
    public BigDecimal getMulta() {
        return multa;
    }

    @DynamoDBAttribute
    public BigDecimal getDesconto() {
        return desconto;
    }

    @DynamoDBAttribute
    public BigDecimal getAbatimento() {
        return abatimento;
    }

    @DynamoDBTypeConverted(converter = LocalDateConverter.class)
    public LocalDate getVencimento(){
        return vencimento;
    }
}